config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  root "top#top"
  get 'top/top'
  resources :universities
  resources :users do
   member do
     get :like_universities
   end
  end
  post 'like/:university_id' => 'likes#like', as:'like'
  delete 'like/:university_id' => 'likes#unlike', as:'unlike'
  resources :plans
end

app/models/agent.rb
class Agent < ActiveRecord::Base
    has_many :contracts
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  belongs_to :agent
  belongs_to :university
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/language.rb
class Language < ActiveRecord::Base
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :university
  validates :university_id, uniqueness: {scope: :user_id}
end

app/models/living.rb
class Living < ActiveRecord::Base
  belongs_to :university
  belongs_to :residence
end

app/models/residence.rb
class Residence < ActiveRecord::Base
end

app/models/university.rb
class University < ActiveRecord::Base
  belongs_to :country
  belongs_to :language
  has_many :likes
  has_many :livings
  has_one :contract
  has_one :agent, through: :contract, source: :agent
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :likes 
  has_many :universities, through: :likes, source: :university
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def like
        university = University.find(params[:university_id])
        like = current_user.likes.build(university_id: university.id)
        like.save
        redirect_to university
    end
    def unlike
        university = University.find(params[:university_id])
        like = current_user.likes.find_by!(university_id: university.id)
        like.destroy!
        redirect_to university
    end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
    def index
    end
    def show
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def top
    @q = University.search(params[:q])
  end
end

app/controllers/universities_controller.rb
class UniversitiesController < ApplicationController
  before_action :set_university, only: [:show, :edit, :update, :destroy]

  # GET /universities
  # GET /universities.json
  def index
    #@universities = University.all
    @q = University.search(params[:q])
    @universities = @q.result(distinct: true)
  end

  # GET /universities/1
  # GET /universities/1.json
  def show
    @liked = current_user.present? && current_user.likes.find_by(university_id: @university.id)
  end

  # GET /universities/new
  def new
    @university = University.new
  end

  # GET /universities/1/edit
  def edit
  end

  # POST /universities
  # POST /universities.json
  def create
    @university = University.new(university_params)

    respond_to do |format|
      if @university.save
        format.html { redirect_to @university, notice: 'University was successfully created.' }
        format.json { render :show, status: :created, location: @university }
      else
        format.html { render :new }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /universities/1
  # PATCH/PUT /universities/1.json
  def update
    respond_to do |format|
      if @university.update(university_params)
        format.html { redirect_to @university, notice: 'University was successfully updated.' }
        format.json { render :show, status: :ok, location: @university }
      else
        format.html { render :edit }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /universities/1
  # DELETE /universities/1.json
  def destroy
    @university.destroy
    respond_to do |format|
      format.html { redirect_to universities_url, notice: 'University was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_university
      @university = University.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def university_params
      params.require(:university).permit(:name, :country_id, :language_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_search_form.html.erb
<%= search_form_for @q, url: universities_path ,class:'ken' do |f| %>
    <div class="row">
      <div class="form-group col-xs-6 col-xs-offset-6">
    <div class="row">
      <div class="col-xs-12">
       <%= f.search_field :name_cont, class: 'form-control', placeholder: 'University' %>
    </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
     　<%= f.search_field :country_name_cont, class: 'form-control',placeholder: 'Country' %>
    </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
       <%= f.search_field :language_name_cont ,class: 'form-control', placeholder: 'Language' %>
    </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
       <%= f.label :livings_residence_id,"Lodging Type", class: 'livings_residence_id' %>
       <%= f.collection_select(:livings_residence_id_eq, Residence.all, :id, :name, include_blank: true)%>
    </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
       <%= f.submit '検索'%>
    </div>
    </div>
    </div>
<% end %>

app/views/plans/index.html.erb
<% @plans.each do |plan| %>
<div class="plan_box">
    <a href="/plans/<%= plan.id %>">
        <img style="height:120px;float:left;" src="http://www.lee.phys.titech.ac.jp/~tanaka/Prof_Tanaka.jpg">
    </a>
    <ul class="float">
        <li>
            <%=plans.name%>
        </li>
        <li>
            <%=plans.city%>
        </li>
        </ul>
        <div class="clerfix">
            </div>
</div>
<% end %>

app/views/top/top.html.erb
<div class="top">
<div class="pic">
   <%= render 'application/search_form' %> 
</div>
</div>

app/views/universities/_form.html.erb
<%= form_for(@university) do |f| %>
  <% if @university.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@university.errors.count, "error") %> prohibited this university from being saved:</h2>

      <ul>
      <% @university.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country_id %><br>
    <%= f.text_field :country_id %>
  </div>
  <div class="field">
    <%= f.label :language_id %><br>
    <%= f.text_field :language_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/universities/edit.html.erb
<h1>Editing University</h1>

<%= render 'form' %>

<%= link_to 'Show', @university %> |
<%= link_to 'Back', universities_path %>

app/views/universities/index.html.erb
<p id="notice"><%= notice %></p>




<div class="container-fluid">
    <div class="row">
    <div class="col-md-3 sidebar">
        
        <%= search_form_for @q, url: universities_path ,class:'ken' do |f| %>
    <div class="row">
      <div class="form-group col-xs-6">
    <div class="row">
      <div class="col-xs-12">
       <%= f.search_field :name_cont, class: 'form-control', placeholder: 'University' %>
    </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
     　<%= f.search_field :country_name_cont, class: 'form-control',placeholder: 'Country' %>
    </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
       <%= f.search_field :language_name_cont ,class: 'form-control', placeholder: 'Language' %>
    </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
       <%= f.label :livings_residence_id,"Lodging Type", class: 'livings_residence_id' %>
       <%= f.collection_select(:livings_residence_id_eq, Residence.all, :id, :name, include_blank: true)%>
    </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
       <%= f.submit '検索'%>
    </div>
    </div>
    </div>
<% end %>

    </div>
    
</div>




<% @universities.each do |university| %>
<div class="row">
        <div class="col-md-6 col-md-offset-3">
          <img style="width:70%" src="<%= university.image %>">
        </div>
        <div class="col-md-3">
        <ul class="detail">
            <li>University : <%= university.name %></li>
            <li>Language : <%= university.language.name %></li>
            <li>Country: <%= university.country.name %></li>
            <li><%= link_to '詳細を見る', university %></li>
        </ul>
        </div>
</div>       
        
<% end %>

app/views/universities/new.html.erb
<h1>New University</h1>

<%= render 'form' %>

<%= link_to 'Back', universities_path %>

app/views/universities/show.html.erb
<img style="width:80%" src="<%= @university.image %>">
<ul class="detail">
    <li>University : <%= @university.name %></li>
    <li>Language : <%= @university.language.name %></li>
    <li>Country: <%= @university.country.name %></li>
</ul>

<div class="favorite_box">
  <% if @liked %>
    <p class="favorite">
      <%= link_to 'お気に入り取消', unlike_path(@university.id),method: :delete %>
    </p>
    <% else %>
     <% if user_signed_in? %>
    <p class="favorite">
      <%= link_to 'お気に入りに登録', like_path(@university.id),method: :post %>
    </p>
     <% else %>
    <p class="favorite">
      <%= link_to 'お気に入りに登録', new_user_registration_path%>
    </p>
     <% end %>
    <% end %>
    
<div>
  <h1>代理店情報</h1>
  <ul>
    <li>
      <%= @university.agent.name %>
    </li>
    <li>
      <%= @university.agent.adress %>
    </li>
    <li>
      <%= @university.agent.tel %>
    </li>
  </ul>
</div>    
    
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p style="font-size:30px;">
    <%= link_to "#{@user.email} さん",edit_user_registration_path %></p>
<p style="font-size:20px;">お気に入りしている大学一覧</p>
 <% @user.universities.each do |university| %>
      <img style="width:80%" src="<%= university.image %>">
<ul class="detail">
    <li>University : <%= university.name %></li>
    <li>Language : <%= university.language.name %></li>
    <li>Country: <%= university.country.name %></li>
    <li><%= link_to '詳細を見る', university %></li>
</ul>
<% end %>